isl_ports:
  eos:
    - Eth1
    - Eth2
  cumulus:
    - swp1
    - swp2
  nxos:
    - Eth1/1
    - Eth1/2
  junos:
    - xe-0/0/0
    - xe-0/0/1

evpn_peers:
  - 10.0.0.21
  - 10.0.0.22

evpn_l3_info:
  - vlan: 999
    vnid: 999
    vlanif: vlan999
    junos_vrf_loopback_ip:
      exit01:
        10.0.0.121/32
      exit02:
        10.0.0.122/32
    vrf: evpn-vrf

internet_vrf: internet-vrf

l2_ifs:
l2vni_ifs:
vid_list: "{{ evpn_l3_info | json_query('[*].vlan') }}"
evpn_vrfs: "{{ evpn_l3_info | json_query('[*].vrf') }}"
l3vni_ifs: "{{ ['vni'] | zip_longest(evpn_l3_info | json_query('[*].vnid') | map('string') | list, fillvalue='vni') | map('join', '') | join(' ') }}"

