isl_ports:
  nxos:
    - Eth1/1
    - Eth1/2
    - Eth1/3
    - Eth1/4
  cumulus:
    - swp1
    - swp2
    - swp3
    - swp4
  eos:
    - Eth1
    - Eth2
    - Eth3
    - Eth4

evpn_peers:
  - 10.0.0.11
  - 10.0.0.12
