---
 - name: Restart switches (Cumulus)
   shell: sleep 1 && shutdown -r 0
   become: yes
   async: 1
   poll: 0
   ignore_errors: true

 - name: Wait for switches to come back up (Cumulus)
   wait_for_connection:
        timeout: 180
        delay: 15
