---
- name: Reload the system
  connection: network_cli
  cli_command:
    command: |
      reload now

- name: reset the connection 
  meta: reset_connection

- name: wait for network device to come back up
  wait_for_connection:
    delay: 10
