---
- name: Reload the system
  connection: network_cli
  cli_command:
    command: |
      reload now

- name: reset the connection 
  meta: reset_connection

 - name: Wait for switches to come back up (Cumulus)
   wait_for_connection:
        timeout: 500
        delay: 30
