---
- name: Configure ISL ports (JunOS)
  connection: network_cli
  cli_config:
    config: |
      set interfaces {{ item }} mtu 9214
      delete interfaces {{ item }} unit 0 family inet dhcp
      set interfaces {{ item }} unit 0 family inet unnumbered-address lo0.0
  with_items: "{{ isl_ports[ansible_network_os] }}"

- name: Configure OSPF Parameters (JunOS)
  connection: network_cli
  cli_config:
    config: |
      set protocols ospf area 0.0.0.0 interface {{ item }}.0 interface-type p2p
  with_items: "{{ isl_ports[ansible_network_os] }}"


