---
- hosts: spine:leaf:exit:dcedge
  gather_facts: false
  roles:
    - role: cfg-hostname
      tags: hostname
    - role: cfg-lo
      tags: loopback
    - role: cfg-lldp
      tags: lldp
  handlers:
    - name: ifup interfaces
      become: yes
      command: ifup -a
    - name: reload FRR
      become: yes
      service:
        name: frr
        state: reloaded

- hosts: spine:leaf
  gather_facts: false
  roles:
    - cfg-features
    - role: cfg-ospf-isl
      tags: isl-ports
    - role: cfg-ospf-underlay
      tags: ospf
    - role: cfg-server-ports
      when: inventory_hostname in groups['leaf']
      tags: server-ports
    - role: cfg-vxlan
      when: inventory_hostname in groups['leaf']
      tags: vxlan
    - role: cfg-evpn
      tags: evpn
    - role: cfg-save
    - role: cfg-reboot
      when: ansible_network_os == "eos"
      tags: reboot
  handlers:
    - name: ifup interfaces
      become: yes
      command: ifup -a
    - name: reload FRR
      become: yes
      service:
        name: frr
        state: reloaded

- hosts: exit
  gather_facts: false
  roles:
    - cfg-features
    - role: cfg-ospf-isl
      tags: isl-ports
    - role: cfg-ospf-underlay
      tags: ospf
    - role: cfg-vxlan
      tags: vxlan
    - role: cfg-exit-isl
      tags: exit-isl
    - role: cfg-evpn
      tags: evpn
    - role: cfg-exit-bgp
      tags: exit-bgp
  handlers:
    - name: ifup interfaces
      become: yes
      command: ifup -a

    - name: reload FRR
      become: yes
      service:
        name: frr
        state: reloaded

- hosts: firewall
  become: yes
  roles:
    - install-frr
    - cfg-fw-interfaces
    - cfg-fw-frr
  
  handlers:
    - name: ifup interfaces
      become: yes
      command: ifup -a
    - name: restart FRR
      become: yes
      service:
        name: frr
        state: reloaded

- hosts: dcedge
  gather_facts: false
  roles:
    - role: cfg-features
    - role: cfg-num-isl
      tags: dcedge-ifs
    - role: cfg-dcedge-bgp
      tags: dcedge-bgp

  handlers:
    - name: ifup interfaces
      become: yes
      command: ifup -a
    - name: restart FRR
      become: yes
      service:
        name: frr
        state: restarted

- hosts: servers
  become: yes
  roles:
    - role: cfg-servers

    
