
---
 - name: Add FRR repo key
   apt_key:
     url: https://deb.frrouting.org/frr/keys.asc
     state: present

 - name: Add FRR repo
   apt_repository:
     repo: deb https://deb.frrouting.org/frr focal frr-stable
     state: present
     update_cache: yes

 - name: Add FRR
   apt:
     name: frr
     state: present
 
 - name: Add FRR pythontools
   apt:
     name: frr-pythontools
     state: present
 
