---
- name: Configure loopback IP (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto lo
      iface lo inet loopback
         address {{ loopback_ip }}
    marker: "# {mark} lo"
  notify:
    - ifup interfaces
