---
- name: Configure loopback IP (EOS)
  connection: network_cli
  cli_config:
    config: |
      int loopback0
        ip address {{ loopback_ip }}

- name: Configure additional VTEP IP, if any (EOS)
  connection: network_cli
  cli_config:
    config: |
      interface Loopback 1
        ip address {{ vtep_ip[ansible_network_os][1] }}
  when: (vtep_ip is defined) and (vtep_ip[ansible_network_os]|length > 1)

- name: Configure VTEP interface (EOS)
  set_fact:
    vtep_iface: "{% if (vtep_ip is defined) and (vtep_ip[ansible_network_os]|length > 1) %} Loopback1 {% else %} Loopback0 {% endif %}"

