---
 - name: Turn off SSH rev DNS lookup
   lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^UseDNS '
      line: UseDNS no

 - name: Restart ssh
   service: name=sshd state=restarted
      
 - name: Copy netplan file
   become: yes
   template: src=netplan.j2 dest=/etc/netplan/02-ansible.yaml

 - name: Apply netplan
   become: yes
   command: netplan apply

 - name: Restart the server
   shell: sleep 1 && shutdown -r 0
   become: yes
   async: 1
   poll: 0
   ignore_errors: true

 - name: Wait for servers to come back up
   wait_for_connection:
        timeout: 180
        delay: 15
