isl_ports:
  cumulus:
    - swp1
    - swp2
  nxos:
    - Eth1/1
    - Eth1/2
  eos:
    - Eth1
    - Eth2
  junos:
    - xe-0/0/0
    - xe-0/0/1

evpn_peers:
  - 10.0.0.21
  - 10.0.0.22

vtep_iface:
  eos:
    Loopback0
  nxos:
    loopback0

# The ID is the VLAN ID; Obviously VLANIDs can only be < 255 with this schemq
anycast_gw_mac: "00:00:00:11:12:{{ item.vlanid }}"

vid_list: "{{ l2_ports[ansible_network_os] | json_query('[*].vlanid') }}"

l2vni_ifs: "{{ ['vni'] | zip_longest(vid_list | map('extract', l2_networks) | list | json_query('[*].vnid'), fillvalue='vni') | map ('join', '') | join(' ') }}"

l3vni_ifs: "{{ ['vni'] | zip_longest(evpn_l3_info | json_query('[*].vnid') | map('string') | list, fillvalue='vni') | map('join', '') | join(' ') }}"

l2_ifs: "{{ l2_ports[ansible_network_os] | json_query('[*].iface') | join(' ') }}"

