---
- name: Configure VNIs (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{ ['vni', l2_networks[item.vlanid].vnid|string]|join('') }}
      iface {{ ['vni', l2_networks[item.vlanid].vnid|string]|join('') }}
        mtu 9200
        vxlan-id {{ l2_networks[item.vlanid].vnid }}
        vxlan-local-tunnelip {{ lo_addr }}
        bridge-learning off
        bridge-access {{ item.vlanid }}
    marker: '# {mark} l2vni-{{ item.vlanid }}'
  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: l2_ports is defined

- name: Configure bridge for EVPN (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto bridge
      iface bridge
        bridge-vlan-aware yes
        bridge-ports  {{ l2_ifs }} {{ l2vni_ifs }} {{ l3vni_ifs }}
        bridge-vids {{ vid_list | join(' ') }}
    marker: '# {mark} bridge'
  notify:
    - ifup interfaces

- name: Configure VRF (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{ item.vrf }}
      iface {{ item.vrf }}
        vrf-table auto
    marker: '# {mark} {{ item.vrf }}'
  with_items: "{{ evpn_l3_info }}"
  notify:
    - ifup interfaces

- name: Configure L3VNI (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{ ['vni', item.vnid|string]|join('') }}
      iface {{ ['vni', item.vnid|string]|join('') }}
        mtu 9200
        vxlan-id {{ item.vnid }}
        vxlan-local-tunnelip {{ lo_addr }}
        bridge-access {{ item.vlan }}
        bridge-learning off

      auto {{ item.vlanif }}
      iface {{ item.vlanif }}
        mtu 9200
        hwaddress {{ hw_address }}
        vlan-id {{ item.vlan }}
        vlan-raw-device bridge
        vrf {{ item.vrf }}
    marker: "# {mark} {{ item }}"
  with_items: "{{ evpn_l3_info }}"
  notify:
    - ifup interfaces

- name: Move SVIs into appropriate VRF
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{ l2_networks[item.vlanid].vlanif }}
      iface {{ l2_networks[item.vlanid].vlanif }}
        vrf {{ l2_networks[item.vlanid].vrf }}
        mtu 9164
        address-virtual {{ anycast_gw_mac }} {{ l2_networks[item.vlanid].ip_address }} 
        vlan-id {{ item.vlanid }}
        vlan-raw-device bridge
    marker: "# {mark} SVI-vlan{{ item.vlanid }}"
  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: l2_ports is defined
  notify:
    - ifup interfaces
