---
- name: Configure VTEP (Junos)
  connection: network_cli
  cli_config:
    config: |
      set protocols evpn encapsulation vxlan
      set protocols evpn extended-vni-list all
      set protocols evpn multicast-mode ingress-replication
      set protocols evpn default-gateway no-gateway-community
      set routing-options forwarding-table chained-composite-next-hop ingress evpn
      set switch-options vtep-source-interface lo0.0
      set switch-options route-distinguisher {{ loopback_ip.split('/')[0] }}:{{ inventory_hostname.split('leaf')[1] }}
      set switch-options vrf-target target:{{ ibgp_asn }}:{{ inventory_hostname.split('leaf')[1] }} auto
      
- name: Configure VNIs (Junos)
  connection: network_cli
  cli_config:
    config: |
      set vlans {{ item.vlanif }} vxlan vni {{ item.vnid }}
  with_items: "{{ l2_networks }}"

- name: Configure L3VNI (Junos)
  connection: network_cli
  cli_config:
    config: |
      set routing-instances {{ item.vrf }} instance-type vrf
      set routing-instances {{ item.vrf }} interface lo0.{{ item.vlan }}
      set interfaces lo0 unit {{ item.vlan }} family inet address {{ item.loopback_ip[inventory_hostname] }}
      set routing-instances {{ item.vrf }} route-distinguisher {{ lo_addr }}:{{item.vlan}}
      set routing-instances {{ item.vrf }} vrf-target target:{{ibgp_asn}}:{{ item.vnid }}
      set routing-instances {{ item.vrf }} vrf-table-label
      set routing-instances {{ item.vrf }} protocols evpn ip-prefix-routes advertise direct-nexthop
      set routing-instances {{ item.vrf }} protocols evpn ip-prefix-routes encapsulation vxlan
      set routing-instances {{ item.vrf }} protocols evpn vni {{ item.vnid }}
  with_items: "{{ evpn_l3_info }}"

- name: Move SVIs into appropriate VRF
  connection: network_cli
  cli_config:
    config: |
      set routing-instances {{ item.vrf }} interface irb.{{ item.id }}
  with_items: "{{ l2_networks }}"

