---
- name: Configure VTEP (Junos)
  connection: network_cli
  cli_config:
    config: |
      set protocols evpn encapsulation vxlan
      set protocols evpn extended-vni-list all
      set protocols evpn multicast-mode ingress-replication
      set protocols evpn default-gateway do-not-advertise
      set routing-options forwarding-table chained-composite-next-hop ingress evpn
      set switch-options vtep-source-interface lo0.0
      set switch-options route-distinguisher {{ lo_addr }}:{{ inventory_hostname[-2:] }}
      set switch-options vrf-target target:{{ ibgp_asn }}:{{ inventory_hostname[-2:] }} auto
      
- name: Configure VNIs (Junos)
  connection: network_cli
  cli_config:
    config: |
      set vlans {{ l2_networks[item.vlanid].vlanif }} vxlan vni {{ l2_networks[item.vlanid].vnid }}
  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: l2_ports is defined

- name: Symmetric routing policy config (Junos)
  connection: network_cli
  cli_config:
    config: |
      set policy-options policy-statement SYMM-EVPN term 1 from protocol direct
      set policy-options policy-statement SYMM-EVPN term 1 then accept
      set policy-options policy-statement SYMM-EVPN term 2 from protocol evpn
      set policy-options policy-statement SYMM-EVPN term 2 then accept
  when: inventory_hostname not in groups['spine']

- name: Configure L3VNI (Junos)
  connection: network_cli
  cli_config:
    config: |
      set routing-instances {{ item.vrf }} instance-type vrf
      set routing-instances {{ item.vrf }} interface lo0.{{ item.vlan }}
      set interfaces lo0 unit {{ item.vlan }} family inet address {{ item.junos_vrf_loopback_ip[inventory_hostname] }}
      set routing-instances {{ item.vrf }} route-distinguisher {{ lo_addr }}:{{item.vlan}}
      set routing-instances {{ item.vrf }} vrf-target target:{{ibgp_asn}}:{{ item.vnid }}
      set routing-instances {{ item.vrf }} vrf-table-label
      set routing-instances {{ item.vrf }} protocols evpn ip-prefix-routes advertise direct-nexthop
      set routing-instances {{ item.vrf }} protocols evpn ip-prefix-routes encapsulation vxlan vni {{ item.vnid }}
      set routing-instances {{ item.vrf }} protocols evpn ip-prefix-routes export SYMM-EVPN
  with_items: "{{ evpn_l3_info }}"
  when: inventory_hostname not in groups['spine']

- name: Move SVIs into appropriate VRF
  connection: network_cli
  cli_config:
    config: |
      set routing-instances {{ l2_networks[item.vlanid].vrf }} interface irb.{{ l2_networks[item.vlanid].vnid }}
  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: l2_ports is defined

