---
- name: Configure NVE/VTEP (NXOS)
  connection: network_cli
  cli_config:
    config: |
      interface nve1
        no shutdown
        host-reachability protocol bgp
        source-interface loopback0
  when: inventory_hostname in groups['leaf']
  tags: vxlan

- name: Configure anycast gateway (NXOS)
  connection: network_cli
  cli_config:
    config: |
      fabric forwarding anycast-gateway-mac {{ anycast_gw_mac }}
  when: inventory_hostname in groups['leaf']
  tags: vxlan

- name: Reconfigure access-list for arp suppression (NXOS)
  connection: network_cli
  cli_config:
    config: |
      hardware access-list tcam region vpc-convergence 0
      hardware access-list tcam region arp-ether 256
  tags: vxlan

- name: Configure VNIs with mcast (NXOS)
  connection: network_cli
  cli_config: 
    config: |
     vlan {{ item.vland }}
       vn-segment {{ l2_networks[item.vlanid].vnid }}

     interface nve1
       !
       member vni {{ l2_networks[item.vlanid].vnid }}
         suppress-arp
         mcast-group {{ item.mcast_grp }}

  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: inventory_hostname in groups['leaf'] and replication == 'mcast'
  tags: vxlan

- name: Configure VNIs with ingress replication (NXOS)
  connection: network_cli
  cli_config: 
    config: |
     vlan {{ item.vlanid }}
       vn-segment {{ l2_networks[item.vlanid].vnid }}

     interface nve1
       !
       member vni {{ l2_networks[item.vlanid].vnid }}
         suppress-arp
         ingress-replication protocol bgp

  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: inventory_hostname in groups['leaf'] and replication != 'mcast'
  tags: vxlan

- name: Configure L3VNI (NXOS)
  connection: network_cli
  cli_config:
    config: |
      vlan {{ item.vlan }}
         vn-segment {{ item.vnid }}

      vrf context {{ item.vrf }}
         vni {{ item.vnid }}
         rd auto
         address-family ipv4 unicast
           route-target both auto
           route-target both auto evpn

      interface {{ item.vlanif }}
        no shut
        vrf member {{ item.vrf }}
        ip forward
        fabric forwarding mode anycast-gateway

      int nve1
        !
        member vni {{ item.vnid }} associate-vrf

  with_items: "{{ evpn_l3_info }}"
  when: inventory_hostname in groups['leaf']
  tags: vxlan, l3vni

