---
- name: Configure OSPF underlay (NXOS)
  connection: network_cli
  cli_config:
    config: |
      int loopback0
        ip router ospf UNDERLAY area 0.0.0.0
      !
      {% if vtep_iface != "loopback0" %}
      interface {{ vtep_iface }}
         ip router ospf UNDERLAY area 0.0.0.0
      !
      {% endif %}
      router ospf UNDERLAY
         router-id {{ lo_addr }}
         log-adjacency-changes
