---
- name: Configure server-facing ports (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    
    block: |
      auto {{ item.iface }}
      iface {{ item.iface }}
         mtu 9164
         bridge-access {{ item.vlanid }}
    marker: "# {mark} l2port-{{ item.iface }}"
  with_items: "{{ l2_ports[ansible_network_os] }}"
  tags: ifcfg

- name: Configure bridge (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto bridge
      iface bridge
        bridge-vlan-aware yes
        bridge-ports {{ l2_ifs }}
        bridge-vids {{ vid_list }}
    marker: '# {mark} bridge'
  tags: ifcfg

- name: Configure VRF (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{ item.vrf }}
      iface {{ item.vrf }}
        vrf-table auto
    marker: "# {mark} vrf-{item.vrf}"
  with_items: "{{ l2_networks }}"
  tags: ifcfg  

- name: Configure SVI (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{ item.vlanif }}
      iface {{ item.vlanif }}
        mtu 9164
        virtual-address {{ item.ip_address }} {{ anycast_gw_mac }}
        vrf {{ item.vrf }}
        vlan-id {{ item.id }}
        vlan-raw-device bridge
    marker: "# {mark} SVI-{{ item.vlanif }}"
  with_items: "{{ l2_networks }}"
  tags: ifcfg

