---
- name: Configure server-facing ports (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    
    block: |
      auto {{ item.iface }}
      iface {{ item.iface }}
         mtu 9164
         bridge-access {{ item.vlanid }}
    marker: "# {mark} l2port-{{ item.iface }}"
  with_items: "{{ l2_ports[ansible_network_os] }}"
  tags: ifcfg
  notify:
    - ifup interfaces

- name: Configure bridge (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto bridge
      iface bridge
        bridge-vlan-aware yes
        bridge-ports {{ l2_ifs }}
        bridge-vids {{ vid_list }}
    marker: '# {mark} bridge'
  tags: ifcfg
  notify:
    - ifup interfaces

- name: Configure VRF (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{ l2_networks[item.vlanid].vrf }}
      iface {{ l2_networks[item.vlanid].vrf }}
        vrf-table auto
    marker: "# {mark} vrf-{l2_networks[item.vlanid].vrf}"
  with_items: "{{ l2_ports[ansible_network_os] }}"
  tags: ifcfg  
  notify:
    - ifup interfaces

- name: Configure SVI (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{ l2_networks[item.vlanid].vlanif }}
      iface {{ l2_networks[item.vlanid].vlanif }}
        mtu 9164
        virtual-address {{ l2_networks[item.vlanid].ip_address }} {{ anycast_gw_mac }}
        vrf {{ l2_networks[item.vlanid].vrf }}
        vlan-id {{ item.vlanid }}
        vlan-raw-device bridge
    marker: "# {mark} SVI-vlan{{ item.vlanid }}"
  with_items: "{{ l2_ports[ansible_network_os] }}"
  tags: ifcfg
  notify:
    - ifup interfaces

