---
- name: Configure server-facing ports (Junos)
  connection: network_cli
  cli_config:
    config: |
      set interfaces {{ item.iface }} unit 0 family ethernet-switching vlan members {{ item.vlanid }}
      delete interfaces {{ item.iface }} unit 0 family inet
  with_items: "{{ l2_ports[ansible_network_os] }}"

- name: Configure SVI (Junos)
  connection: network_cli
  cli_config:
    config: |
      set interfaces irb unit {{ l2_networks[item.vlanid].vnid }} proxy-macip-advertisement
      set interfaces irb unit {{ l2_networks[item.vlanid].vnid }} family inet address {{ l2_networks[item.vlanid].ip_address }}
      set interfaces irb unit {{ l2_networks[item.vlanid].vnid }} mac {{ anycast_gw_mac }}
      set vlans {{ l2_networks[item.vlanid].vlanif }} vlan-id {{ item.vlanid }} l3-interface irb.{{ l2_networks[item.vlanid].vnid }}
  with_items: "{{ l2_ports[ansible_network_os] }}"
