loopback_ip: 10.0.0.11/32
hw_address: 44:39:39:FF:40:95

l2_ports:
  cumulus:
    - iface: swp3
      vlanid: 10
    - iface: swp4
      vlanid: 30
  nxos:
    - iface: Eth1/3
      vlanid: 10
    - iface: Eth1/4
      vlanid: 30
  eos:
    - iface: Eth3
      vlanid: 10
    - iface: Eth4
      vlanid: 30
  junos:
    - iface: xe-0/0/2
      vlanid: 10
    - iface: xe-0/0/3
      vlanid: 30

    
