---
- name: Make FW ISL port routed (EOS)
  connection: network_cli
  cli_config:
    config: |
      int {{ item.iface.split('.')[0] }}
        no switchport
        no shut
  with_items: "{{ default_vrf_firewall_ports[ansible_network_os] }}"

- name: Configure Internet VRF (EOS)
  connection: network_cli
  cli_config:
    config: |
      vrf instance {{ internet_vrf }}
      ip routing vrf {{ internet_vrf }}

- name: Configure FW ports (EOS)
  connection: network_cli
  cli_config:
    config: "{{ lookup('template', 'templates/eos.j2') }}"

- name: Configure DCEdge port (EOS)
  connection: network_cli
  cli_config:
    config: |
      int {{ item.iface }}
        no switchport
        no shut
        vrf {{ item.vrf }}
        ip address {{ item.address }}
  with_items: "{{ dcedge_ports[ansible_network_os] }}"
